# Generated by Django 5.1.4 on 2025-01-12 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idRole', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nameRole', models.CharField(max_length=60)),
                ('dateRole', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['dateRole'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rut', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=80)),
                ('age', models.IntegerField(max_length=2)),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='H', max_length=1)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('idWD', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start', models.DateTimeField(default=True)),
                ('end', models.DateTimeField(default=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
