# Generated by Django 5.1.4 on 2025-01-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_workingday_end_alter_workingday_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingday',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='start',
            field=models.DateTimeField(blank=True),
        ),
    ]
