# Generated by Django 5.1.4 on 2025-01-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignmentsTeams',
            fields=[
                ('idTeam', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Number', models.IntegerField(max_length=15)),
                ('date', models.DateTimeField()),
                ('person', models.ManyToManyField(to='users.user')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
