# Generated by Django 5.1.4 on 2025-01-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentsTeams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsteams',
            name='Number',
            field=models.IntegerField(),
        ),
    ]
