# Generated by Django 5.1.4 on 2025-01-20 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignmentsTeams', '0002_alter_assignmentsteams_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('idBelt', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('beltNum', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayloadCompartment',
            fields=[
                ('id_PC', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bag', models.IntegerField(null=True)),
                ('cargo', models.IntegerField(null=True)),
                ('avih', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rute',
            fields=[
                ('idRute', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('idServices', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('GPU', models.BooleanField(null=True)),
                ('ASU', models.BooleanField(null=True)),
                ('stair', models.BooleanField(null=True)),
                ('parking', models.CharField(max_length=10, null=True)),
                ('others', models.CharField(max_length=200, null=True)),
                ('remarks', models.TextField(max_length=2000, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('idFlight', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('airline', models.CharField(max_length=50)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('arriveNumber', models.IntegerField(blank=True, null=True)),
                ('departureNumber', models.IntegerField(blank=True, null=True)),
                ('registration', models.CharField(max_length=6)),
                ('material', models.CharField(max_length=6)),
                ('date', models.DateField()),
                ('gate', models.CharField(max_length=10)),
                ('STA', models.TimeField()),
                ('STD', models.TimeField()),
                ('ATA', models.TimeField()),
                ('ATD', models.TimeField()),
                ('belt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.belt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workboard.category')),
                ('team', models.ManyToManyField(blank=True, to='assignmentsTeams.assignmentsteams')),
                ('payload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.payloadcompartment')),
                ('rute', models.ManyToManyField(blank=True, to='workboard.rute')),
                ('services', models.ManyToManyField(blank=True, to='workboard.services')),
            ],
        ),
    ]
