# Generated by Django 5.1.4 on 2025-01-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='rute',
        ),
        migrations.AlterField(
            model_name='flight',
            name='ATD',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='others',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='parking',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='services',
            name='remarks',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.DeleteModel(
            name='Rute',
        ),
    ]
