# Generated by Django 5.1.4 on 2025-02-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0002_remove_flight_rute_alter_flight_atd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('idAircraft', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('regristration', models.CharField(max_length=15)),
                ('material', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('idAirline', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('idGate', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('numberGate', models.CharField(max_length=15)),
                ('remote', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rute',
            fields=[
                ('idRute', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='ATA',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='ATD',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='STA',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='STD',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arriveNumber',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='belt',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departureNumber',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='gate',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='material',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='services',
        ),
        migrations.AddField(
            model_name='flight',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.services'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.aircraft'),
        ),
        migrations.CreateModel(
            name='Arrive',
            fields=[
                ('idArrive', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField()),
                ('STA', models.TimeField()),
                ('ATA', models.TimeField(blank=True)),
                ('date', models.DateTimeField()),
                ('belt', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.belt')),
                ('payload', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.payloadcompartment')),
                ('gate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.gate')),
                ('rute', models.ManyToManyField(to='workboard.rute')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='arrive',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.arrive'),
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('idDeparture', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField()),
                ('STD', models.TimeField()),
                ('ATD', models.TimeField(blank=True)),
                ('date', models.DateTimeField()),
                ('payload', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.payloadcompartment')),
                ('gate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.gate')),
                ('rute', models.ManyToManyField(to='workboard.rute')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='departure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.departure'),
        ),
    ]
